project:
  type: book
  output-dir: _book
  pre-render: scripts/update-chapters.R
book:
  title: Course Journal
  author: YOUR NAME
  date: today
  downloads:
  - pdf
  - epub
  chapters:
  - index.qmd
  - entries/2025-09-03-1.qmd
  - entries/2025-09-03-2.qmd
  - entries/2025-09-03.qmd
  - entries/2025-09-15.qmd
  - entries/2025-09-23.qmd
  - entries/2025-09-28.qmd
  - entries/2025-10-07.qmd
  - entries/2025-10-13.qmd
format:
  html:
    toc: true
    number-sections: true
    css: assets/styles.scss
  pdf:
    toc: true
    number-sections: true
